title: LPG Inventory Solutions
url: "" # the base hostname & protocol for your site, e.g. http://example.com
description: >- # this means to ignore newlines until "baseurl:"
  Providing wholesale services for 24 years.
  LPG Inventory Solutions in Hamilton, Ontario, continues to benefit independent retail pharmacies. 
  Obtain products quickly online to receive the same day or by overnight delivery service.
baseurl: "" # the subpath of your site, e.g. /blog
sass:
    load_paths: 
        - _sass
plugins:
  - jekyll-autoprefixer # gem install jekyll-autoprefixer ... required to install this jem beforehand
  - jekyll-environment-variables

autoprefixer:
  browsers:
    - last 4 versions
#    - Safari > 2

exclude:
  - Gemfile
  - Gemfile.lock
  - mailapp.js
